<?php

namespace App\Service;

use App\Entity\AuditLog; use App\Entity\Groupe; use App\Entity\GroupeJoinRequest; use App\Entity\GroupeMember; use App\Entity\Notification; use App\Entity\User;
use App\Repository\GroupeJoinRequestRepository; use App\Repository\GroupeMemberRepository;
use Doctrine\DBAL\Exception\UniqueConstraintViolationException; use Doctrine\ORM\EntityManagerInterface;

final class GroupeMembershipService
{
    public function __construct(private readonly EntityManagerInterface $em, private readonly GroupeMemberRepository $members, private readonly GroupeJoinRequestRepository $requests) {}
    public function join(Groupe $g, User $u): GroupeMember { if ($g->getVisibility() !== Groupe::VISIBILITY_PUBLIC) throw new \LogicException('Cette faction privée nécessite une demande.'); return $this->createMembership($g, $u); }
    public function request(Groupe $g, User $u, ?string $message): GroupeJoinRequest
    {
        $this->assertJoinable($g, $u); if ($g->getVisibility() !== Groupe::VISIBILITY_PRIVATE) throw new \LogicException('Cette faction peut être rejointe directement.'); if ($this->requests->findPending($g,$u)) throw new \LogicException('Une demande est déjà en attente.');
        try { return $this->em->wrapInTransaction(function () use ($g,$u,$message): GroupeJoinRequest { $request=new GroupeJoinRequest($g,$u,$message); $this->em->persist($request); foreach($this->members->findActiveForGroup($g) as $member) if($member->isAdmin()) $this->em->persist((new Notification($member->getUser(),Notification::TYPE_FACTION_JOIN_REQUEST))->setActor($u)->setTarget($request->getId(),Notification::TARGET_TYPE_JOIN_REQUEST)->setContent($u->getUsername().' souhaite rejoindre la faction.')); $this->em->flush(); return $request; }); } catch (UniqueConstraintViolationException) { throw new \LogicException('Une demande est déjà en attente.'); }
    }
    public function accept(GroupeJoinRequest $r, User $actor): GroupeMember
    {
        $this->assertManager($r->getGroup(),$actor); if(!$r->isPending()) throw new \LogicException('Cette demande a déjà été traitée.');
        return $this->em->wrapInTransaction(function () use ($r,$actor): GroupeMember { if($this->members->findActive($r->getGroup(),$r->getRequester())) throw new \LogicException('Cet utilisateur est déjà membre.'); $m=new GroupeMember($r->getGroup(),$r->getRequester()); $r->review(GroupeJoinRequest::ACCEPTED,$actor); $this->em->persist($m); $this->em->persist((new Notification($r->getRequester(),Notification::TYPE_FACTION_JOIN_ACCEPTED))->setActor($actor)->setTarget($r->getGroup()->getId(),Notification::TARGET_TYPE_FACTION)->setContent('Votre demande a été acceptée.')); $this->em->flush(); return $m; });
    }
    public function reject(GroupeJoinRequest $r, User $actor): void { $this->assertManager($r->getGroup(),$actor); $r->review(GroupeJoinRequest::REJECTED,$actor); $this->em->persist((new Notification($r->getRequester(),Notification::TYPE_FACTION_JOIN_REJECTED))->setActor($actor)->setTarget($r->getGroup()->getId(),Notification::TARGET_TYPE_FACTION)->setContent('Votre demande a été refusée.')); $this->em->flush(); }
    public function cancel(Groupe $g, User $requester): void { $r=$this->requests->findPending($g,$requester) ?? throw new \LogicException('Aucune demande en attente.'); $r->review(GroupeJoinRequest::CANCELLED,$requester); $this->em->flush(); }
    public function leave(Groupe $g, User $u): void { $m=$this->requireActive($g,$u); if($m->isOwner()) throw new \LogicException('Le propriétaire doit transférer la propriété ou archiver la faction avant de partir.'); $m->leave(); $this->em->flush(); }
    public function remove(Groupe $g, User $target, User $actor): void { $manager=$this->assertManager($g,$actor); $member=$this->requireActive($g,$target); if($member->isOwner() || ($member->getRole()===GroupeMember::ADMIN && !$manager->isOwner())) throw new \LogicException('Vous ne pouvez pas exclure ce membre.'); $member->leave(GroupeMember::REMOVED); $this->em->persist(new AuditLog($actor,AuditLog::ACTION_FACTION_MEMBER_REMOVED,AuditLog::TARGET_TYPE_FACTION,$g->getId(),'userId='.$target->getId()->toRfc4122())); $this->em->persist((new Notification($target,Notification::TYPE_FACTION_MEMBER_REMOVED))->setActor($actor)->setTarget($g->getId(),Notification::TARGET_TYPE_FACTION)->setContent('Vous avez été retiré de la faction.')); $this->em->flush(); }
    public function changeRole(Groupe $g, User $target, string $role, User $actor): GroupeMember { $manager=$this->assertManager($g,$actor); $member=$this->requireActive($g,$target); if(!in_array($role,[GroupeMember::ADMIN,GroupeMember::MEMBER],true) || $member->isOwner() || !$manager->isOwner()) throw new \LogicException('Ce changement de rôle est interdit.'); $member->changeRole($role); $this->em->persist(new AuditLog($actor,AuditLog::ACTION_FACTION_MEMBER_ROLE_CHANGED,AuditLog::TARGET_TYPE_FACTION,$g->getId(),'userId='.$target->getId()->toRfc4122().';role='.$role)); if($role===GroupeMember::ADMIN)$this->em->persist((new Notification($target,Notification::TYPE_FACTION_MEMBER_PROMOTED))->setActor($actor)->setTarget($g->getId(),Notification::TARGET_TYPE_FACTION)->setContent('Vous êtes désormais administrateur de la faction.')); $this->em->flush(); return $member; }
    public function transferOwnership(Groupe $g, User $target, User $actor): void { $owner=$this->requireActive($g,$actor); if(!$owner->isOwner()) throw new \LogicException('Seul le propriétaire peut transférer la faction.'); $next=$this->requireActive($g,$target); if($next->getUser()->getId()->equals($actor->getId())) throw new \LogicException('Vous êtes déjà propriétaire.'); $this->em->wrapInTransaction(function () use($g,$owner,$next,$actor,$target):void { $owner->changeRole(GroupeMember::ADMIN); $next->changeRole(GroupeMember::OWNER); $this->em->persist(new AuditLog($actor,AuditLog::ACTION_FACTION_OWNERSHIP_TRANSFERRED,AuditLog::TARGET_TYPE_FACTION,$g->getId(),'newOwnerId='.$target->getId()->toRfc4122())); $this->em->flush(); }); }
    private function createMembership(Groupe $g, User $u): GroupeMember { $this->assertJoinable($g,$u); try{return $this->em->wrapInTransaction(function()use($g,$u):GroupeMember{$m=new GroupeMember($g,$u);$this->em->persist($m);$this->em->flush();return $m;});}catch(UniqueConstraintViolationException){throw new \LogicException('Vous êtes déjà membre de cette faction.');} }
    private function assertJoinable(Groupe $g, User $u): void { if(!$g->isActive()) throw new \LogicException('Cette faction est archivée.'); if($u->getStatus()!=='ACTIVE') throw new \LogicException('Ce compte ne peut pas rejoindre une faction.'); if($this->members->findActive($g,$u)) throw new \LogicException('Vous êtes déjà membre de cette faction.'); }
    private function requireActive(Groupe $g, User $u): GroupeMember { return $this->members->findActive($g,$u) ?? throw new \LogicException('Membre actif introuvable.'); }
    private function assertManager(Groupe $g, User $u): GroupeMember { $m=$this->requireActive($g,$u); if(!$m->isAdmin()) throw new \LogicException('Vous ne pouvez pas gérer cette faction.'); return $m; }
}
