<?php
namespace App\Service;
use App\Entity\Groupe;use App\Entity\GroupeJoinRequest;use App\Entity\GroupeMember;use App\Entity\User;use App\Repository\GroupeJoinRequestRepository;use App\Repository\GroupeMemberRepository;use Doctrine\ORM\EntityManagerInterface;
class GroupeMembershipService { public function __construct(private readonly EntityManagerInterface $em,private readonly GroupeMemberRepository $members,private readonly GroupeJoinRequestRepository $requests){}
 public function join(Groupe $g,User $u):GroupeMember|GroupeJoinRequest{if(!$g->isActive())throw new \LogicException('Cette faction est archivée.');if($this->members->findActive($g,$u))throw new \LogicException('Vous êtes déjà membre de cette faction.');if($g->getVisibility()===Groupe::VISIBILITY_PRIVATE)return $this->request($g,$u,null);$m=new GroupeMember($g,$u);$this->em->persist($m);$this->em->flush();return $m;}
 public function request(Groupe $g,User $u,?string $message):GroupeJoinRequest{if($g->getVisibility()!==Groupe::VISIBILITY_PRIVATE)throw new \LogicException('Cette faction peut être rejointe directement.');if($this->members->findActive($g,$u))throw new \LogicException('Vous êtes déjà membre de cette faction.');if($this->requests->findPending($g,$u))throw new \LogicException('Une demande est déjà en attente.');$r=new GroupeJoinRequest($g,$u,$message);$this->em->persist($r);$this->em->flush();return $r;}
 public function accept(GroupeJoinRequest $r,User $actor):GroupeMember{ $this->assertManager($r->getGroup(),$actor);if(!$r->isPending())throw new \LogicException('Cette demande a déjà été traitée.');$m=new GroupeMember($r->getGroup(),$r->getRequester());$r->review(GroupeJoinRequest::ACCEPTED,$actor);$this->em->persist($m);$this->em->flush();return $m;}
 public function leave(Groupe $g,User $u):void{$m=$this->members->findActive($g,$u);if(!$m)throw new \LogicException('Vous n’êtes pas membre de cette faction.');if($m->isOwner())throw new \LogicException('Le propriétaire doit transférer la propriété ou archiver la faction avant de partir.');$m->leave();$this->em->flush();}
 private function assertManager(Groupe $g,User $u):void{$m=$this->members->findActive($g,$u);if(!$m||!in_array($m->getRole(),[GroupeMember::OWNER,GroupeMember::OFFICER],true))throw new \LogicException('Vous ne pouvez pas gérer cette faction.');}}
