name       = "gemlink-frontend"
main       = "frontend-worker.ts"
compatibility_date = "2025-01-01"

[assets]
directory  = "./browser"
binding    = "ASSETS"

[assets.routing]
fallback_mode = "single-page-application"