framework:
    messenger:
        failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed:
                dsn: 'redis://%env(REDIS_HOST)%:6379/messages_failed'

        routing:
            'App\Message\SendEmailMessage': async