<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;use Doctrine\Migrations\AbstractMigration;
final class Version20260806090000 extends AbstractMigration { public function getDescription():string{return 'Factions - enrichit groupe et ajoute membres et demandes';} public function up(Schema $schema):void{
$this->addSql("ALTER TABLE groupe ADD COLUMN slug VARCHAR(120) DEFAULT NULL, ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', ADD COLUMN avatar_url TEXT DEFAULT NULL, ADD COLUMN banner_url TEXT DEFAULT NULL, ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()");
$this->addSql("UPDATE groupe SET slug = 'faction-' || substr(id::text, 1, 8) WHERE slug IS NULL");$this->addSql('ALTER TABLE groupe ALTER COLUMN slug SET NOT NULL');$this->addSql('CREATE UNIQUE INDEX uq_groupe_slug ON groupe (slug)');
$this->addSql("CREATE TABLE groupe_member (id UUID NOT NULL, groupe_id UUID NOT NULL, user_id UUID NOT NULL, role VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE', joined_at TIMESTAMPTZ NOT NULL, left_at TIMESTAMPTZ DEFAULT NULL, created_at TIMESTAMPTZ NOT NULL, PRIMARY KEY(id), CONSTRAINT uq_groupe_member_group_user UNIQUE(groupe_id,user_id), CONSTRAINT fk_groupe_member_group FOREIGN KEY(groupe_id) REFERENCES groupe(id) ON DELETE CASCADE, CONSTRAINT fk_groupe_member_user FOREIGN KEY(user_id) REFERENCES utilisateur(id) ON DELETE CASCADE)");
$this->addSql("INSERT INTO groupe_member (id,groupe_id,user_id,role,status,joined_at,created_at) SELECT uuid_generate_v4(),id,created_by,'OWNER','ACTIVE',created_at,created_at FROM groupe");
$this->addSql("INSERT INTO groupe_member (id,groupe_id,user_id,role,status,joined_at,created_at) SELECT uuid_generate_v4(),groupe_id,user_id,CASE WHEN lower(role)='owner' THEN 'OFFICER' ELSE 'MEMBER' END,'ACTIVE',joined_at,joined_at FROM utilisateur_groupe ug WHERE NOT EXISTS (SELECT 1 FROM groupe_member gm WHERE gm.groupe_id=ug.groupe_id AND gm.user_id=ug.user_id)");
$this->addSql("CREATE UNIQUE INDEX uq_groupe_one_active_owner ON groupe_member(groupe_id) WHERE role='OWNER' AND status='ACTIVE'");$this->addSql('CREATE INDEX idx_groupe_member_group_active ON groupe_member(groupe_id,status)');
$this->addSql("CREATE TABLE groupe_join_request (id UUID NOT NULL, groupe_id UUID NOT NULL, requester_id UUID NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'PENDING', message TEXT DEFAULT NULL, reviewed_by UUID DEFAULT NULL, created_at TIMESTAMPTZ NOT NULL, reviewed_at TIMESTAMPTZ DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT fk_gjr_group FOREIGN KEY(groupe_id) REFERENCES groupe(id) ON DELETE CASCADE, CONSTRAINT fk_gjr_requester FOREIGN KEY(requester_id) REFERENCES utilisateur(id) ON DELETE CASCADE, CONSTRAINT fk_gjr_reviewer FOREIGN KEY(reviewed_by) REFERENCES utilisateur(id) ON DELETE SET NULL)");$this->addSql("CREATE UNIQUE INDEX uq_gjr_pending ON groupe_join_request(groupe_id,requester_id) WHERE status='PENDING'");
$this->addSql("CREATE TABLE conversation (id UUID NOT NULL, type VARCHAR(20) NOT NULL, groupe_id UUID DEFAULT NULL, created_by UUID DEFAULT NULL, direct_key VARCHAR(100) DEFAULT NULL, created_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL, last_message_at TIMESTAMPTZ DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT uq_conversation_direct_key UNIQUE(direct_key), CONSTRAINT fk_conversation_group FOREIGN KEY(groupe_id) REFERENCES groupe(id) ON DELETE CASCADE, CONSTRAINT fk_conversation_creator FOREIGN KEY(created_by) REFERENCES utilisateur(id) ON DELETE SET NULL)");
$this->addSql("CREATE UNIQUE INDEX uq_conversation_faction ON conversation(groupe_id) WHERE type='FACTION'");
$this->addSql("CREATE TABLE conversation_participant (id UUID NOT NULL, conversation_id UUID NOT NULL, user_id UUID NOT NULL, joined_at TIMESTAMPTZ NOT NULL, left_at TIMESTAMPTZ DEFAULT NULL, last_read_at TIMESTAMPTZ DEFAULT NULL, last_read_message_id UUID DEFAULT NULL, is_muted BOOLEAN NOT NULL DEFAULT FALSE, PRIMARY KEY(id), CONSTRAINT uq_conversation_participant UNIQUE(conversation_id,user_id), CONSTRAINT fk_cp_conversation FOREIGN KEY(conversation_id) REFERENCES conversation(id) ON DELETE CASCADE, CONSTRAINT fk_cp_user FOREIGN KEY(user_id) REFERENCES utilisateur(id) ON DELETE CASCADE)");
$this->addSql("CREATE TABLE chat_message (id UUID NOT NULL, conversation_id UUID NOT NULL, author_id UUID NOT NULL, content TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL, edited_at TIMESTAMPTZ DEFAULT NULL, deleted_at TIMESTAMPTZ DEFAULT NULL, PRIMARY KEY(id), CONSTRAINT fk_chat_message_conversation FOREIGN KEY(conversation_id) REFERENCES conversation(id) ON DELETE CASCADE, CONSTRAINT fk_chat_message_author FOREIGN KEY(author_id) REFERENCES utilisateur(id) ON DELETE CASCADE)");$this->addSql('CREATE INDEX idx_chat_message_cursor ON chat_message(conversation_id,created_at DESC,id DESC)');}
public function down(Schema $schema):void{$this->addSql('DROP TABLE chat_message');$this->addSql('DROP TABLE conversation_participant');$this->addSql('DROP TABLE conversation');$this->addSql('DROP TABLE groupe_join_request');$this->addSql('DROP TABLE groupe_member');$this->addSql('DROP INDEX uq_groupe_slug');$this->addSql('ALTER TABLE groupe DROP COLUMN updated_at, DROP COLUMN banner_url, DROP COLUMN avatar_url, DROP COLUMN status, DROP COLUMN slug');}}
