<?php
namespace App\Entity;
use App\Repository\ChatMessageRepository; use DateTimeImmutable; use Doctrine\ORM\Mapping as ORM; use InvalidArgumentException; use LogicException; use Symfony\Component\Uid\Uuid;
#[ORM\Entity(repositoryClass:ChatMessageRepository::class)] #[ORM\Table(name:'chat_message')] #[ORM\Index(name:'idx_chat_message_cursor',fields:['conversation','createdAt','id'])]
class ChatMessage {
 #[ORM\Id,ORM\Column(type:'uuid')]private Uuid $id; #[ORM\ManyToOne(targetEntity:Conversation::class),ORM\JoinColumn(name:'conversation_id',nullable:false,onDelete:'CASCADE')]private Conversation $conversation; #[ORM\ManyToOne(targetEntity:User::class),ORM\JoinColumn(name:'author_id',nullable:false,onDelete:'RESTRICT')]private User $author; #[ORM\Column(type:'text')]private string $content; #[ORM\Column(name:'created_at',type:'datetimetz_immutable')]private DateTimeImmutable $createdAt; #[ORM\Column(name:'edited_at',type:'datetimetz_immutable',nullable:true)]private ?DateTimeImmutable $editedAt=null; #[ORM\Column(name:'deleted_at',type:'datetimetz_immutable',nullable:true)]private ?DateTimeImmutable $deletedAt=null;
 public function __construct(Conversation $conversation,User $author,string $content){$this->id=Uuid::v7();$this->conversation=$conversation;$this->author=$author;$this->createdAt=new DateTimeImmutable();$this->setContent($content,false);} public function getId():Uuid{return $this->id;}public function getConversation():Conversation{return $this->conversation;}public function getAuthor():User{return $this->author;}public function getContent():string{return $this->content;}public function getCreatedAt():DateTimeImmutable{return $this->createdAt;}public function getEditedAt():?DateTimeImmutable{return $this->editedAt;}public function getDeletedAt():?DateTimeImmutable{return $this->deletedAt;}public function isDeleted():bool{return $this->deletedAt!==null;}
 public function edit(string $content):self{if($this->isDeleted())throw new LogicException('Un message supprimé ne peut pas être modifié.');return $this->setContent($content,true);} private function setContent(string $content,bool $edited):self{$content=trim($content);if($content===''||mb_strlen($content)>2000)throw new InvalidArgumentException('Le message doit contenir entre 1 et 2000 caractères.');$this->content=$content;if($edited)$this->editedAt=new DateTimeImmutable();return $this;} public function delete():self{if(!$this->isDeleted())$this->deletedAt=new DateTimeImmutable();return $this;}
}
