<?php
namespace App\Entity;
use App\Repository\ConversationParticipantRepository; use DateTimeImmutable; use Doctrine\ORM\Mapping as ORM; use Symfony\Component\Uid\Uuid;
#[ORM\Entity(repositoryClass: ConversationParticipantRepository::class)] #[ORM\Table(name:'conversation_participant')] #[ORM\UniqueConstraint(name:'uq_conversation_participant',fields:['conversation','user'])]
class ConversationParticipant {
 #[ORM\Id,ORM\Column(type:'uuid')] private Uuid $id; #[ORM\ManyToOne(targetEntity:Conversation::class),ORM\JoinColumn(name:'conversation_id',nullable:false,onDelete:'CASCADE')] private Conversation $conversation; #[ORM\ManyToOne(targetEntity:User::class),ORM\JoinColumn(name:'user_id',nullable:false,onDelete:'CASCADE')] private User $user;
 #[ORM\Column(name:'joined_at',type:'datetimetz_immutable')] private DateTimeImmutable $joinedAt; #[ORM\Column(name:'left_at',type:'datetimetz_immutable',nullable:true)] private ?DateTimeImmutable $leftAt=null; #[ORM\Column(name:'last_read_at',type:'datetimetz_immutable',nullable:true)] private ?DateTimeImmutable $lastReadAt=null; #[ORM\Column(name:'last_read_message_id',type:'uuid',nullable:true)] private ?Uuid $lastReadMessageId=null; #[ORM\Column(name:'is_muted')] private bool $isMuted=false;
 public function __construct(Conversation $conversation,User $user){$this->id=Uuid::v7();$this->conversation=$conversation;$this->user=$user;$this->joinedAt=new DateTimeImmutable();}
 public function getId():Uuid{return $this->id;} public function getConversation():Conversation{return $this->conversation;} public function getUser():User{return $this->user;} public function getJoinedAt():DateTimeImmutable{return $this->joinedAt;} public function getLeftAt():?DateTimeImmutable{return $this->leftAt;} public function getLastReadAt():?DateTimeImmutable{return $this->lastReadAt;} public function getLastReadMessageId():?Uuid{return $this->lastReadMessageId;} public function isMuted():bool{return $this->isMuted;}
 public function markRead(?ChatMessage $message):self{$this->lastReadAt=new DateTimeImmutable();$this->lastReadMessageId=$message?->getId();return $this;} public function setMuted(bool $muted):self{$this->isMuted=$muted;return $this;}
}
