<?php
namespace App\Controller;
use App\Entity\ChatMessage;use App\Entity\Conversation;use App\Entity\User;use App\Service\ChatMessageService;use App\Service\ConversationAccessService;use App\Service\ConversationService;use Doctrine\ORM\EntityManagerInterface;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\JsonResponse;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\Routing\Attribute\Route;use Symfony\Component\Security\Http\Attribute\IsGranted;use Symfony\Component\Uid\Uuid;
#[Route('/api/conversations')]
#[IsGranted('IS_AUTHENTICATED_FULLY')]
final class ConversationController extends AbstractController {
 public function __construct(private readonly EntityManagerInterface $em,private readonly ConversationService $conversations,private readonly ConversationAccessService $access,private readonly ChatMessageService $messages){}
 #[Route('/direct',methods:['POST'])] public function direct(Request $request):JsonResponse {$payload=json_decode($request->getContent(),true);try{$id=Uuid::fromString(is_array($payload)?(string)($payload['userId']??''):'');$other=$this->em->find(User::class,$id);if(!$other instanceof User)return $this->json(['message'=>'Utilisateur introuvable.'],404);$conversation=$this->conversations->direct($this->user(),$other);return $this->json(['id'=>$conversation->getId()->toRfc4122(),'type'=>$conversation->getType()],201);}catch(\InvalidArgumentException $e){return $this->json(['message'=>$e->getMessage()],422);}}
 #[Route('/{id}/messages',methods:['GET'])] public function list(string $id):JsonResponse {$conversation=$this->conversation($id);if(!$conversation)return $this->json(['message'=>'Conversation introuvable.'],404);try{$this->access->assertAccess($conversation,$this->user());}catch(\LogicException $e){return $this->json(['message'=>$e->getMessage()],403);}$messages=$this->em->getRepository(ChatMessage::class)->findBy(['conversation'=>$conversation],['createdAt'=>'DESC'],30);return $this->json(['items'=>array_map(static fn(ChatMessage $message)=>['id'=>$message->getId()->toRfc4122(),'content'=>$message->getContent(),'author'=>['id'=>$message->getAuthor()->getId()->toRfc4122(),'username'=>$message->getAuthor()->getUsername()]],$messages),'nextCursor'=>null,'limit'=>30]);}
 #[Route('/{id}/messages',methods:['POST'])] public function send(string $id,Request $request):JsonResponse {$conversation=$this->conversation($id);if(!$conversation)return $this->json(['message'=>'Conversation introuvable.'],404);$payload=json_decode($request->getContent(),true);try{$message=$this->messages->send($conversation,$this->user(),is_array($payload)&&is_string($payload['content']??null)?$payload['content']:'');return $this->json(['id'=>$message->getId()->toRfc4122(),'content'=>$message->getContent()],201);}catch(\LogicException $e){return $this->json(['message'=>$e->getMessage()],403);}catch(\InvalidArgumentException $e){return $this->json(['message'=>$e->getMessage()],422);}}
 private function conversation(string $id):?Conversation {try{return $this->em->find(Conversation::class,Uuid::fromString($id));}catch(\InvalidArgumentException){return null;}} private function user():User{return $this->getUser();}
}
