<?php
namespace App\Controller;
use App\Entity\Groupe;use App\Entity\GroupeMember;use App\Entity\User;use App\Repository\GroupeMemberRepository;use App\Repository\GroupeRepository;use App\Service\GroupeMembershipService;use App\Service\GroupeService;use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;use Symfony\Component\HttpFoundation\JsonResponse;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\HttpFoundation\Response;use Symfony\Component\Routing\Attribute\Route;use Symfony\Component\Security\Http\Attribute\IsGranted;use Symfony\Component\Uid\Uuid;
#[Route('/api/factions')] final class FactionController extends AbstractController {public function __construct(private readonly GroupeRepository $groups,private readonly GroupeMemberRepository $members,private readonly GroupeService $service,private readonly GroupeMembershipService $membership){}
#[Route('',methods:['GET'])]public function index():JsonResponse{return $this->json(['items'=>array_map($this->serialize(...),$this->groups->findBy(['status'=>Groupe::STATUS_ACTIVE],['createdAt'=>'DESC'],50))]);}
#[Route('',methods:['POST'])]#[IsGranted('IS_AUTHENTICATED_FULLY')]public function create(Request $r):JsonResponse{try{$g=$this->service->create($this->user(),$this->payload($r));return $this->json($this->serialize($g),201);}catch(\InvalidArgumentException $e){return $this->json(['message'=>$e->getMessage()],422);}}
#[Route('/{id}',methods:['GET'])]public function show(string $id):JsonResponse{$g=$this->find($id);if(!$g)return $this->json(['message'=>'Faction introuvable.'],404);if(!$this->isGranted('FACTION_VIEW',$g))return $this->json(['message'=>'Faction introuvable.'],404);return $this->json($this->serialize($g));}
#[Route('/{id}',methods:['PATCH'])]#[IsGranted('IS_AUTHENTICATED_FULLY')]public function edit(string $id,Request $r):JsonResponse{$g=$this->find($id);if(!$g)return $this->json(['message'=>'Faction introuvable.'],404);if(!$this->isGranted('FACTION_EDIT',$g))return $this->json(['message'=>'Accès refusé.'],403);try{return $this->json($this->serialize($this->service->update($g,$this->payload($r))));}catch(\InvalidArgumentException $e){return $this->json(['message'=>$e->getMessage()],422);}}
#[Route('/{id}/join',methods:['POST'])]#[IsGranted('IS_AUTHENTICATED_FULLY')]public function join(string $id):JsonResponse{$g=$this->find($id);if(!$g)return $this->json(['message'=>'Faction introuvable.'],404);try{$x=$this->membership->join($g,$this->user());return $this->json(['status'=>$x instanceof GroupeMember?'JOINED':'REQUESTED'],201);}catch(\LogicException $e){return $this->json(['message'=>$e->getMessage()],409);}}
private function find(string $id):?Groupe{try{return $this->groups->find(Uuid::fromString($id));}catch(\InvalidArgumentException){return null;}}/** @return array<string,mixed> */private function payload(Request $r):array{$x=json_decode($r->getContent(),true);return is_array($x)?$x:[];}private function user():User{return $this->getUser();}private function serialize(Groupe $g):array{$owner=$this->members->findOwner($g);return ['id'=>$g->getId()->toRfc4122(),'name'=>$g->getName(),'slug'=>$g->getSlug(),'description'=>$g->getDescription(),'visibility'=>$g->getVisibility(),'status'=>$g->getStatus(),'createdAt'=>$g->getCreatedAt()->format(DATE_ATOM),'owner'=>$owner?['id'=>$owner->getUser()->getId()->toRfc4122(),'username'=>$owner->getUser()->getUsername()]:null];}}
