name: Backend CI

on:
  pull_request:
  push:
    branches:
      - master
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      - run: composer install --no-interaction

      - run: php bin/console lint:container